interface currencyObject {
    name: string;
    symbol?: string;
    currency?: string;
    
  }
  
interface currencyType{
  [key: string]: currencyObject
}

export const currencySet {
    "AFA": { "name": "Afghan Afghani", "symbol": "؋" },
    "ALL": { "name": "Albanian Lek", "symbol": "Lek" },
    "DZD": { "name": "Algerian Dinar", "symbol": "دج" },
    "AOA": { "name": "Angolan Kwanza", "symbol": "Kz" },
    "ARS": { "name": "Argentine Peso", "symbol": "$" },
    "AMD": { "name": "Armenian Dram", "symbol": "֏" },
    "AWG": { "name": "Aruban Florin", "symbol": "ƒ" },
    "AUD": { "name": "Australian Dollar", "symbol": "$" },
    "AZN": { "name": "Azerbaijani Manat", "symbol": "m" },
    "BSD": { "name": "Bahamian Dollar", "symbol": "B$" },
    "BHD": { "name": "Bahraini Dinar", "symbol": ".د.ب" },
    "BDT": { "name": "Bangladeshi Taka", "symbol": "৳" },
    "BBD": { "name": "Barbadian Dollar", "symbol": "Bds$" },
    "BYR": { "name": "Belarusian Ruble", "symbol": "Br" },
    "BEF": { "name": "Belgian Franc", "symbol": "fr" },
    "BZD": { "name": "Belize Dollar", "symbol": "$" },
    "BMD": { "name": "Bermudan Dollar", "symbol": "$" },
    "BTN": { "name": "Bhutanese Ngultrum", "symbol": "Nu." },
    "BTC": { "name": "Bitcoin", "symbol": "฿" },
    "BOB": { "name": "Bolivian Boliviano", "symbol": "Bs." },
    "BAM": { "name": "Bosnia-Herzegovina Convertible Mark", "symbol": "KM" },
    "BWP": { "name": "Botswanan Pula", "symbol": "P" },
    "BRL": { "name": "Brazilian Real", "symbol": "R$" },
    "GBP": { "name": "British Pound Sterling", "symbol": "£" },
    "BND": { "name": "Brunei Dollar", "symbol": "B$" },
    "BGN": { "name": "Bulgarian Lev", "symbol": "Лв." },
    "BIF": { "name": "Burundian Franc", "symbol": "FBu" },
    "KHR": { "name": "Cambodian Riel", "symbol": "KHR" },
    "CAD": { "name": "Canadian Dollar", "symbol": "$" },
    "CVE": { "name": "Cape Verdean Escudo", "symbol": "$" },
    "KYD": { "name": "Cayman Islands Dollar", "symbol": "$" },
    "XOF": { "name": "CFA Franc BCEAO", "symbol": "CFA" },
    "XAF": { "name": "CFA Franc BEAC", "symbol": "FCFA" },
    "XPF": { "name": "CFP Franc", "symbol": "₣" },
    "CLP": { "name": "Chilean Peso", "symbol": "$" },
    "CNY": { "name": "Chinese Yuan", "symbol": "¥" },
    "COP": { "name": "Colombian Peso", "symbol": "$" },
    "KMF": { "name": "Comorian Franc", "symbol": "CF" },
    "CDF": { "name": "Congolese Franc", "symbol": "FC" },
    "CRC": { "name": "Costa Rican ColÃ³n", "symbol": "₡" },
    "HRK": { "name": "Croatian Kuna", "symbol": "kn" },
    "CUC": { "name": "Cuban Convertible Peso", "symbol": "$, CUC" },
    "CZK": { "name": "Czech Republic Koruna", "symbol": "Kč" },
    "DKK": { "name": "Danish Krone", "symbol": "Kr." },
    "DJF": { "name": "Djiboutian Franc", "symbol": "Fdj" },
    "DOP": { "name": "Dominican Peso", "symbol": "$" },
    "XCD": { "name": "East Caribbean Dollar", "symbol": "$" },
    "EGP": { "name": "Egyptian Pound", "symbol": "ج.م" },
    "ERN": { "name": "Eritrean Nakfa", "symbol": "Nfk" },
    "EEK": { "name": "Estonian Kroon", "symbol": "kr" },
    "ETB": { "name": "Ethiopian Birr", "symbol": "Nkf" },
    "EUR": { "name": "Euro", "symbol": "€" },
    "FKP": { "name": "Falkland Islands Pound", "symbol": "£" },
    "FJD": { "name": "Fijian Dollar", "symbol": "FJ$" },
    "GMD": { "name": "Gambian Dalasi", "symbol": "D" },
    "GEL": { "name": "Georgian Lari", "symbol": "ლ" },
    "DEM": { "name": "German Mark", "symbol": "DM" },
    "GHS": { "name": "Ghanaian Cedi", "symbol": "GH₵" },
    "GIP": { "name": "Gibraltar Pound", "symbol": "£" },
    "GRD": { "name": "Greek Drachma", "symbol": "₯, Δρχ, Δρ" },
    "GTQ": { "name": "Guatemalan Quetzal", "symbol": "Q" },
    "GNF": { "name": "Guinean Franc", "symbol": "FG" },
    "GYD": { "name": "Guyanaese Dollar", "symbol": "$" },
    "HTG": { "name": "Haitian Gourde", "symbol": "G" },
    "HNL": { "name": "Honduran Lempira", "symbol": "L" },
    "HKD": { "name": "Hong Kong Dollar", "symbol": "$" },
    "HUF": { "name": "Hungarian Forint", "symbol": "Ft" },
    "ISK": { "name": "Icelandic KrÃ³na", "symbol": "kr" },
    "INR": { "name": "Indian Rupee", "symbol": "₹" },
    "IDR": { "name": "Indonesian Rupiah", "symbol": "Rp" },
    "IRR": { "name": "Iranian Rial", "symbol": "﷼" },
    "IQD": { "name": "Iraqi Dinar", "symbol": "د.ع" },
    "ILS": { "name": "Israeli New Sheqel", "symbol": "₪" },
    "ITL": { "name": "Italian Lira", "symbol": "L,£" },
    "JMD": { "name": "Jamaican Dollar", "symbol": "J$" },
    "JPY": { "name": "Japanese Yen", "symbol": "¥" },
    "JOD": { "name": "Jordanian Dinar", "symbol": "ا.د" },
    "KZT": { "name": "Kazakhstani Tenge", "symbol": "лв" },
    "KES": { "name": "Kenyan Shilling", "symbol": "KSh" },
    "KWD": { "name": "Kuwaiti Dinar", "symbol": "ك.د" },
    "KGS": { "name": "Kyrgystani Som", "symbol": "лв" },
    "LAK": { "name": "Laotian Kip", "symbol": "₭" },
    "LVL": { "name": "Latvian Lats", "symbol": "Ls" },
    "LBP": { "name": "Lebanese Pound", "symbol": "£" },
    "LSL": { "name": "Lesotho Loti", "symbol": "L" },
    "LRD": { "name": "Liberian Dollar", "symbol": "$" },
    "LYD": { "name": "Libyan Dinar", "symbol": "د.ل" },
    "LTL": { "name": "Lithuanian Litas", "symbol": "Lt" },
    "MOP": { "name": "Macanese Pataca", "symbol": "$" },
    "MKD": { "name": "Macedonian Denar", "symbol": "ден" },
    "MGA": { "name": "Malagasy Ariary", "symbol": "Ar" },
    "MWK": { "name": "Malawian Kwacha", "symbol": "MK" },
    "MYR": { "name": "Malaysian Ringgit", "symbol": "RM" },
    "MVR": { "name": "Maldivian Rufiyaa", "symbol": "Rf" },
    "MRO": { "name": "Mauritanian Ouguiya", "symbol": "MRU" },
    "MUR": { "name": "Mauritian Rupee", "symbol": "₨" },
    "MXN": { "name": "Mexican Peso", "symbol": "$" },
    "MDL": { "name": "Moldovan Leu", "symbol": "L" },
    "MNT": { "name": "Mongolian Tugrik", "symbol": "₮" },
    "MAD": { "name": "Moroccan Dirham", "symbol": "MAD" },
    "MZM": { "name": "Mozambican Metical", "symbol": "MT" },
    "MMK": { "name": "Myanmar Kyat", "symbol": "K" },
    "NAD": { "name": "Namibian Dollar", "symbol": "$" },
    "NPR": { "name": "Nepalese Rupee", "symbol": "₨" },
    "ANG": { "name": "Netherlands Antillean Guilder", "symbol": "ƒ" },
    "TWD": { "name": "New Taiwan Dollar", "symbol": "$" },
    "NZD": { "name": "New Zealand Dollar", "symbol": "$" },
    "NIO": { "name": "Nicaraguan CÃ³rdoba", "symbol": "C$" },
    "NGN": { "name": "Nigerian Naira", "symbol": "₦" },
    "KPW": { "name": "North Korean Won", "symbol": "₩" },
    "NOK": { "name": "Norwegian Krone", "symbol": "kr" },
    "OMR": { "name": "Omani Rial", "symbol": ".ع.ر" },
    "PKR": { "name": "Pakistani Rupee", "symbol": "₨" },
    "PAB": { "name": "Panamanian Balboa", "symbol": "B/." },
    "PGK": { "name": "Papua New Guinean Kina", "symbol": "K" },
    "PYG": { "name": "Paraguayan Guarani", "symbol": "₲" },
    "PEN": { "name": "Peruvian Nuevo Sol", "symbol": "S/." },
    "PHP": { "name": "Philippine Peso", "symbol": "₱" },
    "PLN": { "name": "Polish Zloty", "symbol": "zł" },
    "QAR": { "name": "Qatari Rial", "symbol": "ق.ر" },
    "RON": { "name": "Romanian Leu", "symbol": "lei" },
    "RUB": { "name": "Russian Ruble", "symbol": "₽" },
    "RWF": { "name": "Rwandan Franc", "symbol": "FRw" },
    "SVC": { "name": "Salvadoran ColÃ³n", "symbol": "₡" },
    "WST": { "name": "Samoan Tala", "symbol": "SAT" },
    "SAR": { "name": "Saudi Riyal", "symbol": "﷼" },
    "RSD": { "name": "Serbian Dinar", "symbol": "din" },
    "SCR": { "name": "Seychellois Rupee", "symbol": "SRe" },
    "SLL": { "name": "Sierra Leonean Leone", "symbol": "Le" },
    "SGD": { "name": "Singapore Dollar", "symbol": "$" },
    "SKK": { "name": "Slovak Koruna", "symbol": "Sk" },
    "SBD": { "name": "Solomon Islands Dollar", "symbol": "Si$" },
    "SOS": { "name": "Somali Shilling", "symbol": "Sh.so." },
    "ZAR": { "name": "South African Rand", "symbol": "R" },
    "KRW": { "name": "South Korean Won", "symbol": "₩" },
    "XDR": { "name": "Special Drawing Rights", "symbol": "SDR" },
    "LKR": { "name": "Sri Lankan Rupee", "symbol": "Rs" },
    "SHP": { "name": "St. Helena Pound", "symbol": "£" },
    "SDG": { "name": "Sudanese Pound", "symbol": ".س.ج" },
    "SRD": { "name": "Surinamese Dollar", "symbol": "$" },
    "SZL": { "name": "Swazi Lilangeni", "symbol": "E" },
    "SEK": { "name": "Swedish Krona", "symbol": "kr" },
    "CHF": { "name": "Swiss Franc", "symbol": "CHf" },
    "SYP": { "name": "Syrian Pound", "symbol": "LS" },
    "STD": { "name": "São Tomé and Príncipe Dobra", "symbol": "Db" },
    "TJS": { "name": "Tajikistani Somoni", "symbol": "SM" },
    "TZS": { "name": "Tanzanian Shilling", "symbol": "TSh" },
    "THB": { "name": "Thai Baht", "symbol": "฿" },
    "TOP": { "name": "Tongan Pa'anga", "symbol": "$" },
    "TTD": { "name": "Trinidad & Tobago Dollar", "symbol": "$" },
    "TND": { "name": "Tunisian Dinar", "symbol": "ت.د" },
    "TRY": { "name": "Turkish Lira", "symbol": "₺" },
    "TMT": { "name": "Turkmenistani Manat", "symbol": "T" },
    "UGX": { "name": "Ugandan Shilling", "symbol": "USh" },
    "UAH": { "name": "Ukrainian Hryvnia", "symbol": "₴" },
    "AED": { "name": "United Arab Emirates Dirham", "symbol": "إ.د" },
    "UYU": { "name": "Uruguayan Peso", "symbol": "$" },
    "USD": { "name": "US Dollar", "symbol": "$" },
    "UZS": { "name": "Uzbekistan Som", "symbol": "лв" },
    "VUV": { "name": "Vanuatu Vatu", "symbol": "VT" },
    "VEF": { "name": "Venezuelan BolÃvar", "symbol": "Bs" },
    "VND": { "name": "Vietnamese Dong", "symbol": "₫" },
    "YER": { "name": "Yemeni Rial", "symbol": "﷼" },
    "ZMK": { "name": "Zambian Kwacha", "symbol": "ZK" }
};
export const countryset : currencyType = {
    "AC": { "name": "Ascension Island", "currency": "USD" },
    "AD": { "name": "Andorra", "currency": "EUR" },
    "AE": { "name": "United Arab Emirates", "currency": "AED" },
    "AF": { "name": "Afghanistan", "currency": "AFN" },
    "AG": { "name": "Antigua And Barbuda", "currency": "XCD" },
    "AI": { "name": "Anguilla", "currency": "XCD" },
    "AL": { "name": "Albania", "currency": "ALL" },
    "AM": { "name": "Armenia", "currency": "AMD" },
    "AO": { "name": "Angola", "currency": "AOA" },
    "AQ": { "name": "Antarctica", "currency": "undefined" },
    "AR": { "name": "Argentina", "currency": "ARS" },
    "AS": { "name": "American Samoa", "currency": "USD" },
    "AT": { "name": "Austria", "currency": "EUR" },
    "AU": { "name": "Australia", "currency": "AUD" },
    "AW": { "name": "Aruba", "currency": "AWG" },
    "AX": { "name": "Åland Islands", "currency": "EUR" },
    "AZ": { "name": "Azerbaijan", "currency": "AZN" },
    "BA": { "name": "Bosnia & Herzegovina", "currency": "BAM" },
    "BB": { "name": "Barbados", "currency": "BBD" },
    "BD": { "name": "Bangladesh", "currency": "BDT" },
    "BE": { "name": "Belgium", "currency": "EUR" },
    "BF": { "name": "Burkina Faso", "currency": "XOF" },
    "BG": { "name": "Bulgaria", "currency": "BGN" },
    "BH": { "name": "Bahrain", "currency": "BHD" },
    "BI": { "name": "Burundi", "currency": "BIF" },
    "BJ": { "name": "Benin", "currency": "XOF" },
    "BL": { "name": "Saint Barthélemy", "currency": "EUR" },
    "BM": { "name": "Bermuda", "currency": "BMD" },
    "BN": { "name": "Brunei Darussalam", "currency": "BND" },
    "BO": { "name": "Bolivia, Plurinational State Of", "currency": "BOB" },
    "BQ": { "name": "Bonaire, Saint Eustatius And Saba", "currency": "USD" },
    "BR": { "name": "Brazil", "currency": "BRL" },
    "BS": { "name": "Bahamas", "currency": "BSD" },
    "BT": { "name": "Bhutan", "currency": "INR" },
    "BV": { "name": "Bouvet Island", "currency": "NOK" },
    "BW": { "name": "Botswana", "currency": "BWP" },
    "BY": { "name": "Belarus", "currency": "BYR" },
    "BZ": { "name": "Belize", "currency": "BZD" },
    "CA": { "name": "Canada", "currency": "CAD" },
    "CC": { "name": "Cocos (Keeling) Islands", "currency": "AUD" },
    "CD": { "name": "Democratic Republic Of Congo", "currency": "CDF" },
    "CF": { "name": "Central African Republic", "currency": "XAF" },
    "CG": { "name": "Republic Of Congo", "currency": "XAF" },
    "CH": { "name": "Switzerland", "currency": "CHF" },
    "CI": { "name": "Cote d'Ivoire", "currency": "XOF" },
    "CK": { "name": "Cook Islands", "currency": "NZD" },
    "CL": { "name": "Chile", "currency": "CLP" },
    "CM": { "name": "Cameroon", "currency": "XAF" },
    "CN": { "name": "China", "currency": "CNY" },
    "CO": { "name": "Colombia", "currency": "COP" },
    "CP": { "name": "Clipperton Island", "currency": "EUR" },
    "CR": { "name": "Costa Rica", "currency": "CRC" },
    "CU": { "name": "Cuba", "currency": "CUP" },
    "CV": { "name": "Cabo Verde", "currency": "CVE" },
    "CW": { "name": "Curacao", "currency": "ANG" },
    "CX": { "name": "Christmas Island", "currency": "AUD" },
    "CY": { "name": "Cyprus", "currency": "EUR" },
    "CZ": { "name": "Czech Republic", "currency": "CZK" },
    "DE": { "name": "Germany", "currency": "EUR" },
    "DG": { "name": "Diego Garcia", "currency": "USD" },
    "DJ": { "name": "Djibouti", "currency": "DJF" },
    "DK": { "name": "Denmark", "currency": "DKK" },
    "DM": { "name": "Dominica", "currency": "XCD" },
    "DO": { "name": "Dominican Republic", "currency": "DOP" },
    "DZ": { "name": "Algeria", "currency": "DZD" },
    "EA": { "name": "Ceuta, Mulilla", "currency": "EUR" },
    "EC": { "name": "Ecuador", "currency": "USD" },
    "EE": { "name": "Estonia", "currency": "EUR" },
    "EG": { "name": "Egypt", "currency": "EGP" },
    "EH": { "name": "Western Sahara", "currency": "MAD" },
    "ER": { "name": "Eritrea", "currency": "ERN" },
    "ES": { "name": "Spain", "currency": "EUR" },
    "ET": { "name": "Ethiopia", "currency": "ETB" },
    "EU": { "name": "European Union", "currency": "EUR" },
    "FI": { "name": "Finland", "currency": "EUR" },
    "FJ": { "name": "Fiji", "currency": "FJD" },
    "FK": { "name": "Falkland Islands", "currency": "FKP" },
    "FM": { "name": "Micronesia, Federated States Of", "currency": "USD" },
    "FO": { "name": "Faroe Islands", "currency": "DKK" },
    "FR": { "name": "France", "currency": "EUR" },
    "FX": { "name": "France, Metropolitan", "currency": "EUR" },
    "GA": { "name": "Gabon", "currency": "XAF" },
    "GB": { "name": "United Kingdom", "currency": "GBP" },
    "GD": { "name": "Grenada", "currency": "XCD" },
    "GE": { "name": "Georgia", "currency": "GEL" },
    "GF": { "name": "French Guiana", "currency": "EUR" },
    "GG": { "name": "Guernsey", "currency": "GBP" },
    "GH": { "name": "Ghana", "currency": "GHS" },
    "GI": { "name": "Gibraltar", "currency": "GIP" },
    "GL": { "name": "Greenland", "currency": "DKK" },
    "GM": { "name": "Gambia", "currency": "GMD" },
    "GN": { "name": "Guinea", "currency": "GNF" },
    "GP": { "name": "Guadeloupe", "currency": "EUR" },
    "GQ": { "name": "Equatorial Guinea", "currency": "XAF" },
    "GR": { "name": "Greece", "currency": "EUR" },
    "GS": { "name": "South Georgia And The South Sandwich Islands", "currency": "GBP" },
    "GT": { "name": "Guatemala", "currency": "GTQ" },
    "GU": { "name": "Guam", "currency": "USD" },
    "GW": { "name": "Guinea-bissau", "currency": "XOF" },
    "GY": { "name": "Guyana", "currency": "GYD" },
    "HK": { "name": "Hong Kong", "currency": "HKD" },
    "HM": { "name": "Heard Island And McDonald Islands", "currency": "AUD" },
    "HN": { "name": "Honduras", "currency": "HNL" },
    "HR": { "name": "Croatia", "currency": "HRK" },
    "HT": { "name": "Haiti", "currency": "HTG" },
    "HU": { "name": "Hungary", "currency": "HUF" },
    "IC": { "name": "Canary Islands", "currency": "EUR" },
    "ID": { "name": "Indonesia", "currency": "IDR" },
    "IE": { "name": "Ireland", "currency": "EUR" },
    "IL": { "name": "Israel", "currency": "ILS" },
    "IM": { "name": "Isle Of Man", "currency": "GBP" },
    "IN": { "name": "India", "currency": "INR" },
    "IO": { "name": "British Indian Ocean Territory", "currency": "USD" },
    "IQ": { "name": "Iraq", "currency": "IQD" },
    "IR": { "name": "Iran, Islamic Republic Of", "currency": "IRR" },
    "IS": { "name": "Iceland", "currency": "ISK" },
    "IT": { "name": "Italy", "currency": "EUR" },
    "JE": { "name": "Jersey", "currency": "GBP" },
    "JM": { "name": "Jamaica", "currency": "JMD" },
    "JO": { "name": "Jordan", "currency": "JOD" },
    "JP": { "name": "Japan", "currency": "JPY" },
    "KE": { "name": "Kenya", "currency": "KES" },
    "KG": { "name": "Kyrgyzstan", "currency": "KGS" },
    "KH": { "name": "Cambodia", "currency": "KHR" },
    "KI": { "name": "Kiribati", "currency": "AUD" },
    "KM": { "name": "Comoros", "currency": "KMF" },
    "KN": { "name": "Saint Kitts And Nevis", "currency": "XCD" },
    "KP": { "name": "Korea, Democratic People's Republic Of", "currency": "KPW" },
    "KR": { "name": "Korea, Republic Of", "currency": "KRW" },
    "KW": { "name": "Kuwait", "currency": "KWD" },
    "KY": { "name": "Cayman Islands", "currency": "KYD" },
    "KZ": { "name": "Kazakhstan", "currency": "KZT" },
    "LA": { "name": "Lao People's Democratic Republic", "currency": "LAK" },
    "LB": { "name": "Lebanon", "currency": "LBP" },
    "LC": { "name": "Saint Lucia", "currency": "XCD" },
    "LI": { "name": "Liechtenstein", "currency": "CHF" },
    "LK": { "name": "Sri Lanka", "currency": "LKR" },
    "LR": { "name": "Liberia", "currency": "LRD" },
    "LS": { "name": "Lesotho", "currency": "LSL" },
    "LT": { "name": "Lithuania", "currency": "EUR" },
    "LU": { "name": "Luxembourg", "currency": "EUR" },
    "LV": { "name": "Latvia", "currency": "EUR" },
    "LY": { "name": "Libya", "currency": "LYD" },
    "MA": { "name": "Morocco", "currency": "MAD" },
    "MC": { "name": "Monaco", "currency": "EUR" },
    "MD": { "name": "Moldova", "currency": "MDL" },
    "ME": { "name": "Montenegro", "currency": "EUR" },
    "MF": { "name": "Saint Martin", "currency": "EUR" },
    "MG": { "name": "Madagascar", "currency": "MGA" },
    "MH": { "name": "Marshall Islands", "currency": "USD" },
    "MK": { "name": "Macedonia, The Former Yugoslav Republic Of", "currency": "MKD" },
    "ML": { "name": "Mali", "currency": "XOF" },
    "MM": { "name": "Myanmar", "currency": "MMK" },
    "MN": { "name": "Mongolia", "currency": "MNT" },
    "MO": { "name": "Macao", "currency": "MOP" },
    "MP": { "name": "Northern Mariana Islands", "currency": "USD" },
    "MQ": { "name": "Martinique", "currency": "EUR" },
    "MR": { "name": "Mauritania", "currency": "MRO" },
    "MS": { "name": "Montserrat", "currency": "XCD" },
    "MT": { "name": "Malta", "currency": "EUR" },
    "MU": { "name": "Mauritius", "currency": "MUR" },
    "MV": { "name": "Maldives", "currency": "MVR" },
    "MW": { "name": "Malawi", "currency": "MWK" },
    "MX": { "name": "Mexico", "currency": "MXN" },
    "MY": { "name": "Malaysia", "currency": "MYR" },
    "MZ": { "name": "Mozambique", "currency": "MZN" },
    "NA": { "name": "Namibia", "currency": "NAD" },
    "NC": { "name": "New Caledonia", "currency": "XPF" },
    "NE": { "name": "Niger", "currency": "XOF" },
    "NF": { "name": "Norfolk Island", "currency": "AUD" },
    "NG": { "name": "Nigeria", "currency": "NGN" },
    "NI": { "name": "Nicaragua", "currency": "NIO" },
    "NL": { "name": "Netherlands", "currency": "EUR" },
    "NO": { "name": "Norway", "currency": "NOK" },
    "NP": { "name": "Nepal", "currency": "NPR" },
    "NR": { "name": "Nauru", "currency": "AUD" },
    "NU": { "name": "Niue", "currency": "NZD" },
    "NZ": { "name": "New Zealand", "currency": "NZD" },
    "OM": { "name": "Oman", "currency": "OMR" },
    "PA": { "name": "Panama", "currency": "PAB" },
    "PE": { "name": "Peru", "currency": "PEN" },
    "PF": { "name": "French Polynesia", "currency": "XPF" },
    "PG": { "name": "Papua New Guinea", "currency": "PGK" },
    "PH": { "name": "Philippines", "currency": "PHP" },
    "PK": { "name": "Pakistan", "currency": "PKR" },
    "PL": { "name": "Poland", "currency": "PLN" },
    "PM": { "name": "Saint Pierre And Miquelon", "currency": "EUR" },
    "PN": { "name": "Pitcairn", "currency": "NZD" },
    "PR": { "name": "Puerto Rico", "currency": "USD" },
    "PS": { "name": "Palestinian Territory, Occupied", "currency": "JOD" },
    "PT": { "name": "Portugal", "currency": "EUR" },
    "PW": { "name": "Palau", "currency": "USD" },
    "PY": { "name": "Paraguay", "currency": "PYG" },
    "QA": { "name": "Qatar", "currency": "QAR" },
    "RE": { "name": "Reunion", "currency": "EUR" },
    "RO": { "name": "Romania", "currency": "RON" },
    "RS": { "name": "Serbia", "currency": "RSD" },
    "RU": { "name": "Russian Federation", "currency": "RUB" },
    "RW": { "name": "Rwanda", "currency": "RWF" },
    "SA": { "name": "Saudi Arabia", "currency": "SAR" },
    "SB": { "name": "Solomon Islands", "currency": "SBD" },
    "SC": { "name": "Seychelles", "currency": "SCR" },
    "SD": { "name": "Sudan", "currency": "SDG" },
    "SE": { "name": "Sweden", "currency": "SEK" },
    "SG": { "name": "Singapore", "currency": "SGD" },
    "SH": { "name": "Saint Helena, Ascension And Tristan Da Cunha", "currency": "SHP" },
    "SI": { "name": "Slovenia", "currency": "EUR" },
    "SJ": { "name": "Svalbard And Jan Mayen", "currency": "NOK" },
    "SK": { "name": "Slovakia", "currency": "EUR" },
    "SL": { "name": "Sierra Leone", "currency": "SLL" },
    "SM": { "name": "San Marino", "currency": "EUR" },
    "SN": { "name": "Senegal", "currency": "XOF" },
    "SO": { "name": "Somalia", "currency": "SOS" },
    "SR": { "name": "Suriname", "currency": "SRD" },
    "SS": { "name": "South Sudan", "currency": "SSP" },
    "ST": { "name": "São Tomé and Príncipe", "currency": "STD" },
    "SU": { "name": "USSR", "currency": "RUB" },
    "SV": { "name": "El Salvador", "currency": "USD" },
    "SX": { "name": "Sint Maarten", "currency": "ANG" },
    "SY": { "name": "Syrian Arab Republic", "currency": "SYP" },
    "SZ": { "name": "Swaziland", "currency": "SZL" },
    "TA": { "name": "Tristan de Cunha", "currency": "GBP" },
    "TC": { "name": "Turks And Caicos Islands", "currency": "USD" },
    "TD": { "name": "Chad", "currency": "XAF" },
    "TF": { "name": "French Southern Territories", "currency": "EUR" },
    "TG": { "name": "Togo", "currency": "XOF" },
    "TH": { "name": "Thailand", "currency": "THB" },
    "TJ": { "name": "Tajikistan", "currency": "TJS" },
    "TK": { "name": "Tokelau", "currency": "NZD" },
    "TL": { "name": "East Timor", "currency": "USD" },
    "TM": { "name": "Turkmenistan", "currency": "TMT" },
    "TN": { "name": "Tunisia", "currency": "TND" },
    "TO": { "name": "Tonga", "currency": "TOP" },
    "TR": { "name": "Turkey", "currency": "TRY" },
    "TT": { "name": "Trinidad And Tobago", "currency": "TTD" },
    "TV": { "name": "Tuvalu", "currency": "AUD" },
    "TW": { "name": "Taiwan, Province Of China", "currency": "TWD" },
    "TZ": { "name": "Tanzania, United Republic Of", "currency": "TZS" },
    "UA": { "name": "Ukraine", "currency": "UAH" },
    "UG": { "name": "Uganda", "currency": "UGX" },
    "UK": { "name": "United Kingdom", "currency": "GBP" },
    "UM": { "name": "United States Minor Outlying Islands", "currency": "USD" },
    "US": { "name": "United States", "currency": "USD" },
    "UY": { "name": "Uruguay", "currency": "UYU" },
    "UZ": { "name": "Uzbekistan", "currency": "UZS" },
    "VA": { "name": "Vatican City State", "currency": "EUR" },
    "VC": { "name": "Saint Vincent And The Grenadines", "currency": "XCD" },
    "VE": { "name": "Venezuela, Bolivarian Republic Of", "currency": "VEF" },
    "VG": { "name": "Virgin Islands (British)", "currency": "USD" },
    "VI": { "name": "Virgin Islands (US)", "currency": "USD" },
    "VN": { "name": "Viet Nam", "currency": "VND" },
    "VU": { "name": "Vanuatu", "currency": "VUV" },
    "WF": { "name": "Wallis And Futuna", "currency": "XPF" },
    "WS": { "name": "Samoa", "currency": "WST" },
    "YE": { "name": "Yemen", "currency": "YER" },
    "YT": { "name": "Mayotte", "currency": "EUR" },
    "ZA": { "name": "South Africa", "currency": "ZAR" },
    "ZM": { "name": "Zambia", "currency": "ZMW" },
    "ZW": { "name": "Zimbabwe", "currency": "USD" }
};
export const countryCodes: String[] = ["AFA", "ALL", "DZD", "AOA", "ARS", "AMD", "AWG", "AUD", "AZN", "BSD", "BHD", "BDT", "BBD", "BYR", "BEF", "BZD", "BMD", "BTN", "BTC", "BOB", "BAM", "BWP", "BRL", "GBP", "BND", "BGN", "BIF", "KHR", "CAD", "CVE", "KYD", "XOF", "XAF", "XPF", "CLP", "CNY", "COP", "KMF", "CDF", "CRC", "HRK", "CUC", "CZK", "DKK", "DJF", "DOP", "XCD", "EGP", "ERN", "EEK", "ETB", "EUR", "FKP", "FJD", "GMD", "GEL", "DEM", "GHS", "GIP", "GRD", "GTQ", "GNF", "GYD", "HTG", "HNL", "HKD", "HUF", "ISK", "INR", "IDR", "IRR", "IQD", "ILS", "ITL", "JMD", "JPY", "JOD", "KZT", "KES", "KWD", "KGS", "LAK", "LVL", "LBP", "LSL", "LRD", "LYD", "LTL", "MOP", "MKD", "MGA", "MWK", "MYR", "MVR", "MRO", "MUR", "MXN", "MDL", "MNT", "MAD", "MZM", "MMK", "NAD", "NPR", "ANG", "TWD", "NZD", "NIO", "NGN", "KPW", "NOK", "OMR", "PKR", "PAB", "PGK", "PYG", "PEN", "PHP", "PLN", "QAR", "RON", "RUB", "RWF", "SVC", "WST", "SAR", "RSD", "SCR", "SLL", "SGD", "SKK", "SBD", "SOS", "ZAR", "KRW", "XDR", "LKR", "SHP", "SDG", "SRD", "SZL", "SEK", "CHF", "SYP", "STD", "TJS", "TZS", "THB", "TOP", "TTD", "TND", "TRY", "TMT", "UGX", "UAH", "AED", "UYU", "USD", "UZS", "VUV", "VEF", "VND", "YER", "ZMK"];
